import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header'
import { Toaster } from '@/components/ui/sonner'
import { UserProvider } from '@/lib/auth'
import retrieveUserFromSession from '@/utils/getUser'
import type { Metadata } from 'next'
import { League_Script, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
})

const leagueScript = League_Script({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-league-script",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const userPromise = retrieveUserFromSession()
  return (
    <html lang='en'>
      <body className={`${poppins.className} ${leagueScript.variable}`} suppressHydrationWarning>
        <UserProvider userPromise={userPromise}>
          <Toaster richColors closeButton />
          <Header />
          <main>{children}</main>
          <Footer />
        </UserProvider>
      </body>
    </html>
  )
}
